In [ ]:
import numpy as np
import os

save_dir = "/mnt/d/Projects/recoscale/data/colab_export/embeddings/"
output_path = "/mnt/d/Projects/recoscale/data/colab_export/title_embeddings.dat"

files = sorted([f for f in os.listdir(save_dir) if f.startswith("emb_")])

#get total size + embedding dim
total_rows = 0
embedding_dim = None

for f in files:
    arr = np.load(os.path.join(save_dir, f))
    total_rows += arr.shape[0]
    if embedding_dim is None:
        embedding_dim = arr.shape[1]
    del arr 

print(f"Total rows: {total_rows}, dim: {embedding_dim}")

#create memmap
memmap = np.memmap(
    output_path,
    dtype="float32",
    mode="w+",
    shape=(total_rows, embedding_dim)
)

#fill memmap chunk by chunk
start = 0

for f in files:
    print(f"Processing {f}")

    chunk = np.load(os.path.join(save_dir, f))
    end = start + chunk.shape[0]

    memmap[start:end] = chunk

    start = end
    del chunk 

#flush to disk
memmap.flush()

print("Done ✅")

Total rows: 7966869, dim: 384
Processing emb_0_500000.npy
Processing emb_1000000_1500000.npy
Processing emb_1500000_2000000.npy
Processing emb_2000000_2500000.npy
Processing emb_2500000_3000000.npy
Processing emb_3000000_3500000.npy
Processing emb_3500000_4000000.npy
Processing emb_4000000_4500000.npy
Processing emb_4500000_5000000.npy
Processing emb_5000000_5500000.npy
Processing emb_500000_1000000.npy
Processing emb_5500000_6000000.npy
Processing emb_6000000_6500000.npy
Processing emb_6500000_7000000.npy
Processing emb_7000000_7500000.npy
Processing emb_7500000_7966869.npy
Done ✅


In [5]:
emb = np.memmap(
    "D:/projects/recoscale/two_tower/data/title_embeddings.dat",
    dtype="float32",
    mode="r",
    shape=(1534814, 384)
)
print(emb.shape)

(1534814, 384)


In [6]:
print(emb[0][:5])
print(emb[100000][:5])
print(emb[-1][:5])

[-0.11378626  0.09956108 -0.1235974  -0.03853815 -0.01143878]
[-0.00448588 -0.08409975  0.04901919  0.09762545  0.04604775]
[ 0.02564183  0.05162198 -0.04989435 -0.07185039 -0.08325258]


In [12]:
chunk = np.load("/mnt/d/projects/recoscale/data/colab_export/embeddings/emb_0_500000.npy")

print(np.allclose(chunk[0], emb[0]))

True


In [ ]:
import numpy as np

# You must know or infer these
dtype = np.float32
shape = (N, 384)  # e.g., (1000, 768)

embeddings = np.memmap("embeddings.dat", dtype=dtype, mode="r", shape=shape)

print("Shape:", embeddings.shape)
print("Dtype:", embeddings.dtype)

In [1]:
import numpy as np
import pandas as pd

df = pd.read_parquet("D:/projects/recoscale/two_tower/data/item_features")
df.head()


,parent_asin,title,price,average_rating,rating_number,main_category,store_encoded,item_idx
0,0321689577,Physical Geology,10.23,4.1,105,0,236148,123371
1,0528881469,Rand McNally 528881469 7-inch Intelliroute TND...,21.99,3.6,73,1,11424,12379
2,0761169377,Eyelike Stickers: Ocean,6.29,4.6,2145,0,227488,4791
3,0793836301,The Boxer (The Terra Nova Series),21.99,4.3,44,0,349589,352168
4,0810930935,The Watch,38.00,4.1,156,0,286084,10417


In [4]:
df.shape

(1534814, 8)

In [ ]:


item_features = np.load(ITEM_FEATURES_PATH)
total_items = item_features.shape[0]

self._title_mmap = np.memmap(
    TITLE_EMBEDDINGS_PATH,
    dtype="float32",
    mode="r",
    shape=(total_items, TITLE_DIM),
)